#docker compose up -d
services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin12345"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./sqlserver:/docker-entrypoint-initdb.d
    entrypoint: >
      /bin/bash -c "
      /docker-entrypoint-initdb.d/init.sh &
      /opt/mssql/bin/sqlservr
      "

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: universidad
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # Ejecuta automáticamente cualquier .sql al arrancar por primera vez
      - ./postgres/estudiante.sql:/docker-entrypoint-initdb.d/01_estudiante.sql

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle
    environment:
      ORACLE_PASSWORD: oracle
      APP_USER: universidad
      APP_USER_PASSWORD: universidad
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./oracle/matricula.sql:/container-entrypoint-initdb.d/01_matricula.sql

volumes:
  sqlserver_data:
  postgres_data:
  oracle_data: